### ISSUE TITLE
Install instructions...

### ISSUE THREAD

**Issue by benthorner** [AdamWhittingham/vim-config#17]
Hi Adam! I think your config install miniskirt (love spellchecker) might be wrong: should it be [[ -e ~/.vimrc ]] || ... or possibly [[ -e ~/.vim/vimrc ]] && ... instead of [[ -e ~/.vim/vimrc ]] || ...?

**Comment by AdamWhittingham** [comment]
Hey Ben!

`~/.vimrc` should be a symlink to `~/.vim/vimrc`. Is this causing an issue with installing?

**Comment by benthorner** [comment]
That bit makes sense. I think the problem is that you do a test for [[ -e ~/.vim/vimrc ]] and only do the link if it *doesn't* exist (at least, that seems to be the behaviour when I try it). Changing the || to && seems to fix it...

**Comment by AdamWhittingham** [comment]
Can you give a little more context about what the issue is and what isn't
working please?

**Comment by benthorner** [comment]
Sure - I'm a master of confusion! I was just trying to install your config, so I didn't have a .vimrc file (yet). The readme says to run the install script, which in turn runs ```[[ -e ~/.vim/vimrc ]] || ln -s ~/.vim/vimrc ~/.vimrc```, which does nothing for me as ```[[ -e ~/.vim/vimrc ]]``` returns true, meaning ```ln -s ~/.vim/vimrc ~/.vimrc``` isn't executed and your config doesn't get installed :(. Changing the || to && would solve that.

**Comment by benthorner** [comment]
Any clearer? I must try to start describing either the problem, or the solution, and not both at the same time!

**Comment by AdamWhittingham** [comment]
Very good point; as you said, it should be testing for [[ ~/. vimrc ]]
instead. Good spot, shows up that I forgot to remove my symlink when
trialling the script. Derp!

I'll happily merge a PR if you have a fix ready, else I'll fix it when I'm
next at a laptop with 3 minutes to spare.

Thanks for raising this!
